/**
 * Mock Data for Job Scout Demo
 * Realistic job data for Kenya/East Africa software engineering positions
 */

import type {
  Company,
  Job,
  JobSource,
  DashboardStats,
  ScrapeLog,
  User,
} from "@/types";

// ============================================
// Demo User
// ============================================

export const mockUser: User = {
  id: "demo-user-001",
  email: "demo@jobscout.co.ke",
  full_name: "Demo User",
  is_active: true,
  is_admin: false,
  created_at: "2024-01-15T10:00:00Z",
  updated_at: "2024-02-01T14:30:00Z",
};

// ============================================
// Companies
// ============================================

export const mockCompanies: Company[] = [
  {
    id: "comp-001",
    name: "Safaricom PLC",
    logo_url: "https://logo.clearbit.com/safaricom.co.ke",
    careers_url: "https://www.safaricom.co.ke/careers",
    is_active: true,
    scraper_type: "dynamic",
    scrape_frequency_hours: 6,
    last_scraped_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    created_at: "2024-01-10T08:00:00Z",
    updated_at: "2024-02-01T12:00:00Z",
  },
  {
    id: "comp-002",
    name: "Equity Bank",
    logo_url: "https://logo.clearbit.com/equitybank.co.ke",
    careers_url: "https://equitygroupholdings.com/careers",
    is_active: true,
    scraper_type: "static",
    scrape_frequency_hours: 12,
    last_scraped_at: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    created_at: "2024-01-10T08:00:00Z",
    updated_at: "2024-02-01T12:00:00Z",
  },
  {
    id: "comp-003",
    name: "M-KOPA",
    logo_url: "https://logo.clearbit.com/m-kopa.com",
    careers_url: "https://m-kopa.com/careers",
    is_active: true,
    scraper_type: "api",
    scrape_frequency_hours: 4,
    last_scraped_at: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    created_at: "2024-01-12T09:00:00Z",
    updated_at: "2024-02-01T10:00:00Z",
  },
  {
    id: "comp-004",
    name: "Andela",
    logo_url: "https://logo.clearbit.com/andela.com",
    careers_url: "https://andela.com/careers",
    is_active: true,
    scraper_type: "dynamic",
    scrape_frequency_hours: 8,
    last_scraped_at: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    created_at: "2024-01-08T10:00:00Z",
    updated_at: "2024-02-01T11:00:00Z",
  },
  {
    id: "comp-005",
    name: "Twiga Foods",
    logo_url: "https://logo.clearbit.com/twiga.com",
    careers_url: "https://twiga.com/careers",
    is_active: true,
    scraper_type: "static",
    scrape_frequency_hours: 12,
    last_scraped_at: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    created_at: "2024-01-14T08:00:00Z",
    updated_at: "2024-02-01T09:00:00Z",
  },
  {
    id: "comp-006",
    name: "Cellulant",
    logo_url: "https://logo.clearbit.com/cellulant.com",
    careers_url: "https://cellulant.io/careers",
    is_active: true,
    scraper_type: "dynamic",
    scrape_frequency_hours: 6,
    last_scraped_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    created_at: "2024-01-11T10:00:00Z",
    updated_at: "2024-02-01T14:00:00Z",
  },
  {
    id: "comp-007",
    name: "Kenya Airways",
    logo_url: "https://logo.clearbit.com/kenya-airways.com",
    careers_url: "https://www.kenya-airways.com/careers",
    is_active: true,
    scraper_type: "static",
    scrape_frequency_hours: 24,
    last_scraped_at: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
    created_at: "2024-01-15T08:00:00Z",
    updated_at: "2024-02-01T08:00:00Z",
  },
  {
    id: "comp-008",
    name: "Microsoft ADC",
    logo_url: "https://logo.clearbit.com/microsoft.com",
    careers_url: "https://careers.microsoft.com/nairobi",
    is_active: true,
    scraper_type: "api",
    scrape_frequency_hours: 4,
    last_scraped_at: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    created_at: "2024-01-09T10:00:00Z",
    updated_at: "2024-02-01T15:00:00Z",
  },
  {
    id: "comp-009",
    name: "Google Kenya",
    logo_url: "https://logo.clearbit.com/google.com",
    careers_url: "https://careers.google.com/locations/nairobi",
    is_active: true,
    scraper_type: "api",
    scrape_frequency_hours: 4,
    last_scraped_at: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    created_at: "2024-01-08T08:00:00Z",
    updated_at: "2024-02-01T16:00:00Z",
  },
  {
    id: "comp-010",
    name: "Flutterwave",
    logo_url: "https://logo.clearbit.com/flutterwave.com",
    careers_url: "https://flutterwave.com/careers",
    is_active: false,
    scraper_type: "dynamic",
    scrape_frequency_hours: 8,
    last_scraped_at: new Date(Date.now() - 48 * 60 * 60 * 1000).toISOString(),
    created_at: "2024-01-13T10:00:00Z",
    updated_at: "2024-01-30T12:00:00Z",
  },
  {
    id: "comp-011",
    name: "KCB Bank",
    logo_url: "https://logo.clearbit.com/kcbgroup.com",
    careers_url: "https://ke.kcbgroup.com/careers",
    is_active: true,
    scraper_type: "static",
    scrape_frequency_hours: 12,
    last_scraped_at: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
    created_at: "2024-01-10T08:00:00Z",
    updated_at: "2024-02-01T10:00:00Z",
  },
  {
    id: "comp-012",
    name: "Jumia Kenya",
    logo_url: "https://logo.clearbit.com/jumia.co.ke",
    careers_url: "https://group.jumia.com/careers",
    is_active: true,
    scraper_type: "dynamic",
    scrape_frequency_hours: 8,
    last_scraped_at: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    created_at: "2024-01-12T09:00:00Z",
    updated_at: "2024-02-01T11:00:00Z",
  },
];

// ============================================
// Job Sources
// ============================================

export const mockSources: JobSource[] = [
  {
    id: "src-001",
    company_id: "comp-001",
    company: mockCompanies[0],
    source_type: "careers_page",
    source_url: "https://www.safaricom.co.ke/careers/technology",
    is_active: true,
    scraper_status: "active",
    last_scraped_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    jobs_found_count: 12,
    created_at: "2024-01-10T08:00:00Z",
    updated_at: "2024-02-01T12:00:00Z",
  },
  {
    id: "src-002",
    company_id: "comp-002",
    company: mockCompanies[1],
    source_type: "careers_page",
    source_url: "https://equitygroupholdings.com/careers/technology",
    is_active: true,
    scraper_status: "active",
    last_scraped_at: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    jobs_found_count: 8,
    created_at: "2024-01-10T08:00:00Z",
    updated_at: "2024-02-01T12:00:00Z",
  },
  {
    id: "src-003",
    company_id: "comp-003",
    company: mockCompanies[2],
    source_type: "careers_page",
    source_url: "https://m-kopa.com/careers/engineering",
    is_active: true,
    scraper_status: "active",
    last_scraped_at: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    jobs_found_count: 15,
    created_at: "2024-01-12T09:00:00Z",
    updated_at: "2024-02-01T10:00:00Z",
  },
  {
    id: "src-004",
    company_id: "comp-004",
    company: mockCompanies[3],
    source_type: "careers_page",
    source_url: "https://andela.com/careers/engineering",
    is_active: true,
    scraper_status: "active",
    last_scraped_at: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    jobs_found_count: 22,
    created_at: "2024-01-08T10:00:00Z",
    updated_at: "2024-02-01T11:00:00Z",
  },
  {
    id: "src-005",
    company_id: "comp-005",
    company: mockCompanies[4],
    source_type: "careers_page",
    source_url: "https://twiga.com/careers",
    is_active: true,
    scraper_status: "error",
    last_scraped_at: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    last_error: "Connection timeout after 30 seconds",
    jobs_found_count: 5,
    created_at: "2024-01-14T08:00:00Z",
    updated_at: "2024-02-01T09:00:00Z",
  },
  {
    id: "src-006",
    company_id: "comp-006",
    company: mockCompanies[5],
    source_type: "careers_page",
    source_url: "https://cellulant.io/careers",
    is_active: true,
    scraper_status: "active",
    last_scraped_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    jobs_found_count: 9,
    created_at: "2024-01-11T10:00:00Z",
    updated_at: "2024-02-01T14:00:00Z",
  },
  {
    id: "src-007",
    company_id: "comp-008",
    company: mockCompanies[7],
    source_type: "careers_page",
    source_url: "https://careers.microsoft.com/nairobi",
    is_active: true,
    scraper_status: "active",
    last_scraped_at: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    jobs_found_count: 18,
    created_at: "2024-01-09T10:00:00Z",
    updated_at: "2024-02-01T15:00:00Z",
  },
  {
    id: "src-008",
    company_id: "comp-009",
    company: mockCompanies[8],
    source_type: "careers_page",
    source_url: "https://careers.google.com/locations/nairobi",
    is_active: true,
    scraper_status: "active",
    last_scraped_at: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    jobs_found_count: 14,
    created_at: "2024-01-08T08:00:00Z",
    updated_at: "2024-02-01T16:00:00Z",
  },
  {
    id: "src-009",
    company_id: "comp-001",
    company: mockCompanies[0],
    source_type: "linkedin",
    source_url: "https://linkedin.com/company/safaricom/jobs",
    is_active: true,
    scraper_status: "paused",
    last_scraped_at: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
    jobs_found_count: 6,
    created_at: "2024-01-15T10:00:00Z",
    updated_at: "2024-02-01T08:00:00Z",
  },
  {
    id: "src-010",
    company_id: "comp-011",
    company: mockCompanies[10],
    source_type: "careers_page",
    source_url: "https://ke.kcbgroup.com/careers/it",
    is_active: true,
    scraper_status: "active",
    last_scraped_at: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
    jobs_found_count: 7,
    created_at: "2024-01-10T08:00:00Z",
    updated_at: "2024-02-01T10:00:00Z",
  },
];

// ============================================
// Jobs
// ============================================

export const mockJobs: Job[] = [
  // Safaricom Jobs
  {
    id: "job-001",
    title: "Senior Software Engineer - M-Pesa",
    company_id: "comp-001",
    company: mockCompanies[0],
    source_id: "src-001",
    description: "Join our M-Pesa engineering team to build the next generation of mobile money solutions. You will be working on high-scale distributed systems processing millions of transactions daily.",
    requirements: [
      "5+ years of experience in software development",
      "Strong proficiency in Java, Kotlin, or Go",
      "Experience with microservices architecture",
      "Knowledge of financial systems and payment processing",
      "Experience with Kubernetes and cloud platforms",
    ],
    location: "Nairobi, Kenya",
    job_type: "full_time",
    experience_level: "senior",
    salary_min: 350000,
    salary_max: 550000,
    salary_currency: "KES",
    application_url: "https://safaricom.co.ke/careers/senior-software-engineer",
    status: "new",
    first_seen_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    last_seen_at: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
  },
  {
    id: "job-002",
    title: "DevOps Engineer",
    company_id: "comp-001",
    company: mockCompanies[0],
    source_id: "src-001",
    description: "We are looking for a DevOps Engineer to help us build and maintain our CI/CD pipelines and cloud infrastructure.",
    requirements: [
      "3+ years of DevOps experience",
      "Strong knowledge of AWS or Azure",
      "Experience with Terraform and Ansible",
      "Kubernetes certification preferred",
    ],
    location: "Nairobi, Kenya",
    job_type: "full_time",
    experience_level: "mid",
    salary_min: 250000,
    salary_max: 400000,
    salary_currency: "KES",
    application_url: "https://safaricom.co.ke/careers/devops-engineer",
    status: "active",
    first_seen_at: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    last_seen_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  // M-KOPA Jobs
  {
    id: "job-003",
    title: "Backend Engineer - Python",
    company_id: "comp-003",
    company: mockCompanies[2],
    source_id: "src-003",
    description: "Join M-KOPA to build technology that brings clean energy to Africa. Work on our IoT platform connecting millions of solar devices.",
    requirements: [
      "3+ years Python development experience",
      "Experience with Django or FastAPI",
      "Knowledge of PostgreSQL and Redis",
      "Understanding of IoT systems is a plus",
    ],
    location: "Nairobi, Kenya (Hybrid)",
    job_type: "full_time",
    experience_level: "mid",
    salary_min: 200000,
    salary_max: 350000,
    salary_currency: "KES",
    application_url: "https://m-kopa.com/careers/backend-engineer",
    status: "new",
    first_seen_at: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    last_seen_at: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
  },
  {
    id: "job-004",
    title: "Mobile Engineer - Flutter",
    company_id: "comp-003",
    company: mockCompanies[2],
    source_id: "src-003",
    description: "Build mobile applications that serve millions of customers across Africa. Work with Flutter to create beautiful, performant apps.",
    requirements: [
      "2+ years Flutter development experience",
      "Published apps on Play Store/App Store",
      "Experience with state management (Riverpod/Bloc)",
      "Knowledge of offline-first architecture",
    ],
    location: "Nairobi, Kenya (Remote)",
    job_type: "full_time",
    experience_level: "mid",
    salary_min: 180000,
    salary_max: 320000,
    salary_currency: "KES",
    application_url: "https://m-kopa.com/careers/mobile-engineer",
    status: "new",
    first_seen_at: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    last_seen_at: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
  },
  // Andela Jobs
  {
    id: "job-005",
    title: "Senior Full-Stack Engineer",
    company_id: "comp-004",
    company: mockCompanies[3],
    source_id: "src-004",
    description: "Work with global clients on cutting-edge projects. Full remote position with competitive compensation.",
    requirements: [
      "5+ years full-stack development experience",
      "Proficiency in React/Next.js and Node.js",
      "Experience with TypeScript",
      "Strong communication skills in English",
    ],
    location: "Remote (Kenya)",
    job_type: "remote",
    experience_level: "senior",
    salary_min: 4000,
    salary_max: 7000,
    salary_currency: "USD",
    application_url: "https://andela.com/careers/senior-fullstack",
    status: "active",
    first_seen_at: new Date(Date.now() - 48 * 60 * 60 * 1000).toISOString(),
    last_seen_at: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 48 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "job-006",
    title: "Junior Software Developer",
    company_id: "comp-004",
    company: mockCompanies[3],
    source_id: "src-004",
    description: "Start your career with Andela. Learn from senior engineers while working on real projects for global clients.",
    requirements: [
      "Computer Science degree or equivalent",
      "Knowledge of at least one programming language",
      "Eagerness to learn and grow",
      "Good communication skills",
    ],
    location: "Remote (Kenya)",
    job_type: "remote",
    experience_level: "entry",
    salary_min: 1500,
    salary_max: 2500,
    salary_currency: "USD",
    application_url: "https://andela.com/careers/junior-developer",
    status: "new",
    first_seen_at: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
    last_seen_at: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
  },
  // Microsoft Jobs
  {
    id: "job-007",
    title: "Software Engineer II - Azure",
    company_id: "comp-008",
    company: mockCompanies[7],
    source_id: "src-007",
    description: "Join Microsoft Africa Development Center in Nairobi. Work on Azure cloud services used by millions worldwide.",
    requirements: [
      "BS/MS in Computer Science",
      "3+ years software development experience",
      "Proficiency in C#, Java, or C++",
      "Experience with cloud platforms",
      "Strong problem-solving skills",
    ],
    location: "Nairobi, Kenya",
    job_type: "full_time",
    experience_level: "mid",
    salary_min: 400000,
    salary_max: 700000,
    salary_currency: "KES",
    application_url: "https://careers.microsoft.com/job/swe2-azure",
    status: "active",
    first_seen_at: new Date(Date.now() - 72 * 60 * 60 * 1000).toISOString(),
    last_seen_at: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 72 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "job-008",
    title: "Principal Software Engineering Manager",
    company_id: "comp-008",
    company: mockCompanies[7],
    source_id: "src-007",
    description: "Lead a team of engineers building next-generation cloud infrastructure at Microsoft ADC Nairobi.",
    requirements: [
      "10+ years software development experience",
      "5+ years engineering management experience",
      "Track record of shipping large-scale systems",
      "Experience with distributed systems",
    ],
    location: "Nairobi, Kenya",
    job_type: "full_time",
    experience_level: "executive",
    salary_min: 800000,
    salary_max: 1500000,
    salary_currency: "KES",
    application_url: "https://careers.microsoft.com/job/principal-sem",
    status: "active",
    first_seen_at: new Date(Date.now() - 120 * 60 * 60 * 1000).toISOString(),
    last_seen_at: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 120 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
  },
  // Google Jobs
  {
    id: "job-009",
    title: "Software Engineer, Machine Learning",
    company_id: "comp-009",
    company: mockCompanies[8],
    source_id: "src-008",
    description: "Work on ML models that power Google products used by billions. Based at our Nairobi office.",
    requirements: [
      "MS/PhD in Computer Science or related field",
      "Experience with TensorFlow or PyTorch",
      "Strong foundation in ML algorithms",
      "Published research is a plus",
    ],
    location: "Nairobi, Kenya",
    job_type: "full_time",
    experience_level: "senior",
    salary_min: 500000,
    salary_max: 900000,
    salary_currency: "KES",
    application_url: "https://careers.google.com/jobs/ml-engineer-nairobi",
    status: "new",
    first_seen_at: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    last_seen_at: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
  },
  // Equity Bank Jobs
  {
    id: "job-010",
    title: "Core Banking Systems Developer",
    company_id: "comp-002",
    company: mockCompanies[1],
    source_id: "src-002",
    description: "Work on Equity Bank's core banking platform serving millions of customers across East Africa.",
    requirements: [
      "4+ years experience in banking systems",
      "Knowledge of T24/Temenos or similar CBS",
      "Experience with Oracle/SQL Server",
      "Understanding of banking regulations",
    ],
    location: "Nairobi, Kenya",
    job_type: "full_time",
    experience_level: "mid",
    salary_min: 280000,
    salary_max: 450000,
    salary_currency: "KES",
    application_url: "https://equitybank.co.ke/careers/core-banking",
    status: "active",
    first_seen_at: new Date(Date.now() - 96 * 60 * 60 * 1000).toISOString(),
    last_seen_at: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 96 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
  },
  // Cellulant Jobs
  {
    id: "job-011",
    title: "Payments Integration Engineer",
    company_id: "comp-006",
    company: mockCompanies[5],
    source_id: "src-006",
    description: "Build payment integrations across Africa. Work with mobile money, card networks, and bank APIs.",
    requirements: [
      "3+ years payments experience",
      "Knowledge of payment protocols (ISO 8583, etc.)",
      "Experience with REST APIs",
      "Understanding of PCI DSS compliance",
    ],
    location: "Nairobi, Kenya",
    job_type: "full_time",
    experience_level: "mid",
    salary_min: 220000,
    salary_max: 380000,
    salary_currency: "KES",
    application_url: "https://cellulant.io/careers/payments-engineer",
    status: "active",
    first_seen_at: new Date(Date.now() - 48 * 60 * 60 * 1000).toISOString(),
    last_seen_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 48 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  // KCB Bank Jobs
  {
    id: "job-012",
    title: "Cybersecurity Analyst",
    company_id: "comp-011",
    company: mockCompanies[10],
    source_id: "src-010",
    description: "Protect KCB Bank's digital infrastructure. Monitor threats and respond to security incidents.",
    requirements: [
      "3+ years in cybersecurity",
      "CISSP or CEH certification",
      "Experience with SIEM tools",
      "Knowledge of banking security standards",
    ],
    location: "Nairobi, Kenya",
    job_type: "full_time",
    experience_level: "mid",
    salary_min: 300000,
    salary_max: 500000,
    salary_currency: "KES",
    application_url: "https://kcbgroup.com/careers/cybersecurity",
    status: "active",
    first_seen_at: new Date(Date.now() - 72 * 60 * 60 * 1000).toISOString(),
    last_seen_at: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 72 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
  },
  // More diverse jobs
  {
    id: "job-013",
    title: "Frontend Developer - React",
    company_id: "comp-012",
    company: mockCompanies[11],
    source_id: "src-002",
    description: "Build the user interface for Jumia's e-commerce platform serving millions of customers.",
    requirements: [
      "2+ years React experience",
      "TypeScript proficiency",
      "Experience with Next.js",
      "Mobile-first design thinking",
    ],
    location: "Nairobi, Kenya",
    job_type: "full_time",
    experience_level: "mid",
    salary_min: 150000,
    salary_max: 280000,
    salary_currency: "KES",
    application_url: "https://jumia.com/careers/frontend",
    status: "new",
    first_seen_at: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    last_seen_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "job-014",
    title: "Data Engineer",
    company_id: "comp-001",
    company: mockCompanies[0],
    source_id: "src-001",
    description: "Build data pipelines processing terabytes of M-Pesa transaction data daily.",
    requirements: [
      "3+ years data engineering experience",
      "Proficiency in Python and SQL",
      "Experience with Spark/Kafka",
      "Knowledge of data warehousing",
    ],
    location: "Nairobi, Kenya",
    job_type: "full_time",
    experience_level: "mid",
    salary_min: 300000,
    salary_max: 480000,
    salary_currency: "KES",
    application_url: "https://safaricom.co.ke/careers/data-engineer",
    status: "new",
    first_seen_at: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    last_seen_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "job-015",
    title: "QA Automation Engineer",
    company_id: "comp-003",
    company: mockCompanies[2],
    source_id: "src-003",
    description: "Build test automation frameworks for M-KOPA's IoT and mobile platforms.",
    requirements: [
      "3+ years QA experience",
      "Experience with Selenium/Appium",
      "Knowledge of CI/CD pipelines",
      "Programming skills in Python or JavaScript",
    ],
    location: "Nairobi, Kenya (Hybrid)",
    job_type: "full_time",
    experience_level: "mid",
    salary_min: 180000,
    salary_max: 300000,
    salary_currency: "KES",
    application_url: "https://m-kopa.com/careers/qa-engineer",
    status: "active",
    first_seen_at: new Date(Date.now() - 36 * 60 * 60 * 1000).toISOString(),
    last_seen_at: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 36 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
  },
];

// ============================================
// Dashboard Stats
// ============================================

export const mockDashboardStats: DashboardStats = {
  total_jobs: mockJobs.length,
  new_jobs_today: mockJobs.filter((j) => j.status === "new").length,
  active_sources: mockSources.filter((s) => s.scraper_status === "active").length,
  total_sources: mockSources.length,
  scrapes_today: 24,
  failed_scrapes_today: 2,
  alerts_sent_today: 8,
};

// ============================================
// Scrape Logs
// ============================================

export const mockScrapeLogs: ScrapeLog[] = [
  {
    id: "log-001",
    source_id: "src-001",
    source: mockSources[0],
    status: "completed",
    jobs_found: 12,
    jobs_new: 2,
    jobs_updated: 3,
    started_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    completed_at: new Date(Date.now() - 2 * 60 * 60 * 1000 + 45000).toISOString(),
    duration_seconds: 45,
  },
  {
    id: "log-002",
    source_id: "src-003",
    source: mockSources[2],
    status: "completed",
    jobs_found: 15,
    jobs_new: 3,
    jobs_updated: 1,
    started_at: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    completed_at: new Date(Date.now() - 1 * 60 * 60 * 1000 + 38000).toISOString(),
    duration_seconds: 38,
  },
  {
    id: "log-003",
    source_id: "src-005",
    source: mockSources[4],
    status: "failed",
    jobs_found: 0,
    jobs_new: 0,
    jobs_updated: 0,
    error_message: "Connection timeout after 30 seconds",
    started_at: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    completed_at: new Date(Date.now() - 24 * 60 * 60 * 1000 + 30000).toISOString(),
    duration_seconds: 30,
  },
  {
    id: "log-004",
    source_id: "src-008",
    source: mockSources[7],
    status: "completed",
    jobs_found: 14,
    jobs_new: 1,
    jobs_updated: 2,
    started_at: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    completed_at: new Date(Date.now() - 30 * 60 * 1000 + 52000).toISOString(),
    duration_seconds: 52,
  },
];

// ============================================
// Helper Functions
// ============================================

export function getNewJobs(limit: number = 10): Job[] {
  return mockJobs
    .filter((j) => j.status === "new")
    .sort((a, b) => new Date(b.first_seen_at).getTime() - new Date(a.first_seen_at).getTime())
    .slice(0, limit);
}

export function getErrorSources(): JobSource[] {
  return mockSources.filter((s) => s.scraper_status === "error");
}

export function getJobsByCompany(companyId: string): Job[] {
  return mockJobs.filter((j) => j.company_id === companyId);
}

export function getSourcesByCompany(companyId: string): JobSource[] {
  return mockSources.filter((s) => s.company_id === companyId);
}

export function getCompanyById(id: string): Company | undefined {
  return mockCompanies.find((c) => c.id === id);
}

export function getJobById(id: string): Job | undefined {
  return mockJobs.find((j) => j.id === id);
}

export function getSourceById(id: string): JobSource | undefined {
  return mockSources.find((s) => s.id === id);
}
